import { nanoid } from "nanoid";
import type { SpendingDetail } from "../types/types";

export const sample: SpendingDetail[] = [
  {
    id: nanoid(),
    year: 2025,
    month: 9,
    day: 1,
    description: "월급",
    amount: 3500000,
    isExpenditure: false,
    paymentMethod: "카드",
    category: "salary",
  },
  {
    id: nanoid(),
    year: 2025,
    month: 9,
    day: 3,
    description: "마트 장보기",
    amount: 85000,
    isExpenditure: true,
    paymentMethod: "카드",
    category: "food",
  },
  {
    id: nanoid(),
    year: 2025,
    month: 9,
    day: 5,
    description: "전기요금",
    amount: 62000,
    isExpenditure: true,
    paymentMethod: "카드",
    category: "living",
  },
  {
    id: nanoid(),
    year: 2025,
    month: 9,
    day: 8,
    description: "지하철 교통비",
    amount: 35000,
    isExpenditure: true,
    paymentMethod: "현금",
    category: "transport",
  },
  {
    id: nanoid(),
    year: 2025,
    month: 9,
    day: 12,
    description: "영화 관람",
    amount: 28000,
    isExpenditure: true,
    paymentMethod: "카드",
    category: "cultureLeisure",
  },
  {
    id: nanoid(),
    year: 2025,
    month: 9,
    day: 15,
    description: "화장품 구매",
    amount: 120000,
    isExpenditure: true,
    paymentMethod: "카드",
    category: "shoppingBeauty",
  },
  {
    id: nanoid(),
    year: 2025,
    month: 9,
    day: 18,
    description: "친구 결혼 축의금",
    amount: 100000,
    isExpenditure: true,
    paymentMethod: "현금",
    category: "unclassified",
  },
  {
    id: nanoid(),
    year: 2025,
    month: 9,
    day: 20,
    description: "약국 의약품",
    amount: 45000,
    isExpenditure: true,
    paymentMethod: "카드",
    category: "medicalHealth",
  },
  {
    id: nanoid(),
    year: 2025,
    month: 9,
    day: 25,
    description: "부모님 용돈",
    amount: 300000,
    isExpenditure: false,
    paymentMethod: "현금",
    category: "allowance",
  },
  {
    id: nanoid(),
    year: 2025,
    month: 9,
    day: 28,
    description: "회식 식대",
    amount: 55000,
    isExpenditure: true,
    paymentMethod: "카드",
    category: "food",
  },

  // October 2025
  {
    id: nanoid(),
    year: 2025,
    month: 10,
    day: 1,
    description: "월급",
    amount: 3500000,
    isExpenditure: false,
    paymentMethod: "카드",
    category: "salary",
  },
  {
    id: nanoid(),
    year: 2025,
    month: 10,
    day: 2,
    description: "관리비",
    amount: 150000,
    isExpenditure: true,
    paymentMethod: "카드",
    category: "living",
  },
  {
    id: nanoid(),
    year: 2025,
    month: 10,
    day: 5,
    description: "편의점",
    amount: 18000,
    isExpenditure: true,
    paymentMethod: "현금",
    category: "food",
  },
  {
    id: nanoid(),
    year: 2025,
    month: 10,
    day: 7,
    description: "택시비",
    amount: 22000,
    isExpenditure: true,
    paymentMethod: "카드",
    category: "transport",
  },
  {
    id: nanoid(),
    year: 2025,
    month: 10,
    day: 10,
    description: "헬스장 회비",
    amount: 80000,
    isExpenditure: true,
    paymentMethod: "카드",
    category: "cultureLeisure",
  },
  {
    id: nanoid(),
    year: 2025,
    month: 10,
    day: 13,
    description: "의류 쇼핑",
    amount: 250000,
    isExpenditure: true,
    paymentMethod: "카드",
    category: "shoppingBeauty",
  },
  {
    id: nanoid(),
    year: 2025,
    month: 10,
    day: 15,
    description: "부업 수입",
    amount: 500000,
    isExpenditure: false,
    paymentMethod: "카드",
    category: "otherIncome",
  },
  {
    id: nanoid(),
    year: 2025,
    month: 10,
    day: 18,
    description: "치과 치료",
    amount: 180000,
    isExpenditure: true,
    paymentMethod: "카드",
    category: "medicalHealth",
  },
  {
    id: nanoid(),
    year: 2025,
    month: 10,
    day: 22,
    description: "커피숍",
    amount: 12000,
    isExpenditure: true,
    paymentMethod: "현금",
    category: "food",
  },
  {
    id: nanoid(),
    year: 2025,
    month: 10,
    day: 25,
    description: "주유비",
    amount: 70000,
    isExpenditure: true,
    paymentMethod: "카드",
    category: "transport",
  },
  {
    id: nanoid(),
    year: 2025,
    month: 10,
    day: 28,
    description: "주유비",
    amount: 70000,
    isExpenditure: true,
    paymentMethod: "카드",
    category: "transport",
  },
  {
    id: nanoid(),
    year: 2025,
    month: 10,
    day: 28,
    description: "주유비",
    amount: 70000,
    isExpenditure: true,
    paymentMethod: "카드",
    category: "transport",
  },
  {
    id: nanoid(),
    year: 2025,
    month: 10,
    day: 28,
    description: "인터넷 요금",
    amount: 35000,
    isExpenditure: true,
    paymentMethod: "카드",
    category: "living",
  },

  // November 2025
  {
    id: nanoid(),
    year: 2025,
    month: 11,
    day: 1,
    description: "월급",
    amount: 3500000,
    isExpenditure: false,
    paymentMethod: "카드",
    category: "salary",
  },
  {
    id: nanoid(),
    year: 2025,
    month: 11,
    day: 3,
    description: "수퍼마켓 장보기",
    amount: 95000,
    isExpenditure: true,
    paymentMethod: "카드",
    category: "food",
  },
  {
    id: nanoid(),
    year: 2025,
    month: 11,
    day: 6,
    description: "미용실",
    amount: 65000,
    isExpenditure: true,
    paymentMethod: "현금",
    category: "shoppingBeauty",
  },
  {
    id: nanoid(),
    year: 2025,
    month: 11,
    day: 9,
    description: "도서 구입",
    amount: 42000,
    isExpenditure: true,
    paymentMethod: "카드",
    category: "cultureLeisure",
  },
  {
    id: nanoid(),
    year: 2025,
    month: 11,
    day: 11,
    description: "버스 교통카드 충전",
    amount: 50000,
    isExpenditure: true,
    paymentMethod: "현금",
    category: "transport",
  },
  {
    id: nanoid(),
    year: 2025,
    month: 11,
    day: 14,
    description: "수도요금",
    amount: 28000,
    isExpenditure: true,
    paymentMethod: "카드",
    category: "living",
  },
  {
    id: nanoid(),
    year: 2025,
    month: 11,
    day: 16,
    description: "건강검진",
    amount: 150000,
    isExpenditure: true,
    paymentMethod: "카드",
    category: "medicalHealth",
  },
  {
    id: nanoid(),
    year: 2025,
    month: 11,
    day: 18,
    description: "배달음식",
    amount: 35000,
    isExpenditure: true,
    paymentMethod: "카드",
    category: "food",
  },
];
